export const courseNames = [
    "Computer Science",
    "Engineering",
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Psychology",
    "Business Administration",
    "Economics",
    "History",
    "Political Science",
    "English Literature",
    "Sociology",
    "Environmental Science",
    "Art History",
    "Music",
    "Philosophy",
    "Geology",
    "Foreign Languages",
    "Nursing",
    "Education",
    "Nutrition",
    "Astronomy",
    "Health Sciences",
    "Medicine",
    "Dentistry",
    "Law",
    "Architecture",
    "Fine Arts",
    "Theater",
    "Film Studies",
    "Communication",
    "Criminal Justice",
    "Information Technology",
    "Cybersecurity",
    "Data Science",
    "Robotics",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Aerospace Engineering",
    "Chemical Engineering",
    "Biomedical Engineering",
    "Materials Science",
    "Environmental Engineering",
    "Geophysics",
    "Microbiology",
    "Genetics",
    "Cell Biology",
    "Zoology",
    "Botany",
    "Anthropology",
    "Archaeology",
    "Linguistics",
    "Classical Studies",
    "Gender Studies",
    "Social Work",
    "Public Health",
    "Dietetics",
    "Physical Therapy",
    "Occupational Therapy",
    "Speech Pathology",
    "Counseling Psychology",
    "Industrial-Organizational Psychology",
    "Clinical Psychology",
    "Neuroscience",
    "Sustainable Agriculture",
    "Forestry",
    "Wildlife Biology",
    "Marine Biology",
    "Meteorology",
    "Oceanography",
    "Astrophysics",
    "Astrobiology",
    "Marketing",
    "Finance",
    "Accounting",
    "Management",
    "Human Resources",
    "Entrepreneurship",
    "International Relations",
    "Public Policy",
    "Sustainable Development",
    "International Business",
    "Humanities",
    "Social Sciences",
    "Natural Sciences",
    "Liberal Arts",
    "Environmental Studies",
    "Ethics",
    "Philosophy of Mind",
    "Cognitive Science",
    "Artificial Intelligence",
    "Machine Learning",
    "Quantum Physics",
    "Theoretical Physics",
    "Organic Chemistry",
    "Inorganic Chemistry",
    "Physical Chemistry",
    "Biochemistry",
    "Microeconomics",
    "Macroeconomics",
    "Statistics",
    "Probability Theory",
    "Linear Algebra",
    "Differential Equations",
    "Calculus",
    "Topology",
    "Abstract Algebra",
    "Number Theory",
    "Geometry",
    "Ethnomusicology",
    "World History",
    "Ancient History",
    "Contemporary Art",
    "Renaissance Art",
    "Ancient Art",
];